spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: 123456
app:
  jwtSecret: someSecretKey
  jwtExpirationMs: 3600000
  jwtRefreshExpirationMs: 86400000

cdn:
  upload-path: /Users/ecagataydogan/Desktop/cdn
  host: http://localhost:8080/cdn/

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true